name: Checks
on: push

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git rewrite rule
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@main
      - name: Flake Check
        run: nix flake check
