name: Checks
on: push

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@main
      - name: Flake Check
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          nix flake check
